apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-backend
  namespace: workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-backend
  template:
    metadata:
      labels:
        app: workflow-backend
    spec:
      containers:
      - name: backend
        image: 542088537076.dkr.ecr.eu-west-1.amazonaws.com/workflow-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "workflow-db.c5s8ycc4qywm.eu-west-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "WorkflowPass123!"
        - name: DB_NAME
          value: "workflow"
        - name: JWT_SECRET
          value: "my-secret-key"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
