apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
  namespace: workflow
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_NAME: "workflow"
  DB_USER: "admin"
  # DB_HOST will be set via environment variable in deployment