apiVersion: v1
kind: Namespace
metadata:
  name: workflow
  labels:
    name: workflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-backend
  namespace: workflow
  labels:
    app: workflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-backend
  template:
    metadata:
      labels:
        app: workflow-backend
    spec:
      containers:
      - name: backend
        image: 542088537076.dkr.ecr.eu-west-1.amazonaws.com/workflow-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_NAME
          value: "workflow"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "WorkflowPass123!"
        - name: JWT_SECRET
          value: "workflow-super-secret-jwt-key-2024"
        - name: DB_HOST
          value: "workflow-db.c5s8ycc4qywm.eu-west-1.rds.amazonaws.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
